### ISSUE TITLE
Link to Instagram

### ISSUE THREAD

**Issue by acrois** [JohnnyIrvin/Website#55]
**Is your feature request related to a problem? Please describe.**
There are various social media links in the footer. Your Instagram is not there.

**Describe the solution you'd like**
A link to your Instagram.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by JohnnyIrvin** [comment]
Looks like I forgot. 🤣

**Comment by JohnnyIrvin** [comment]
Repaired.  Validated in testing environment. Updated snapshots.

Here is picture
![image](https://user-images.githubusercontent.com/16859882/184726671-7b668fd1-30bc-4db3-87b3-a82ddb9baaf1.png)


Merging and squashing -- WIll autoclose.
